### ISSUE TITLE
Import scripts at deploy

### ISSUE THREAD

**Issue by crisp2u** [permeance/liferay-scripting-helper#1]
Hi guys, I'm loving this plugin and I started using in my workflow. I was wondering if there is a way to preload the scripts via import functionality at deployment, it would be easy to provide scripts on multiple deployments...

Thanks!

**Comment by cmaggiulli** [comment]
Can you elaborate a bit?  Are you saying you wish to actually run scripts at deployment or just that you would like to package/save them at deployment?

**Comment by crisp2u** [comment]
For now just package them, running on deployment is another beast and I'm not really sure what is the best approach
