### ISSUE TITLE
Liferay 7 Security Manager

### ISSUE THREAD

**Issue by crisp2u** [permeance/liferay-scripting-helper#3]
Hi Guys,

I'm testing your liferay 7 branch and i noticed that I don't have access to classes like JSONFactoryUtil. I guess it has to do with Security Manager, I guess it used to be configurable via liferay-plugin-package.properties but that's been removed and migrated to the bundle settings i guess. Any idea how to do that ? 

Thanks

**Comment by cwho** [comment]
I've just updated branch 7.0.x, please have a go again and see if it has been fixed. I've turned on dynamic packages import and it works now locally on my test instance.

**Comment by crisp2u** [comment]
Sorry, I was rude and did not provide an update on this. I've been using that build for a while with no issues 👍 Lately, i'm seeing some activity regarding compatibility with 7. Do you plan an official release for 7 soon ? If so can you reconsider #1 ? Thanks for all your effort!
